eureka.client.serviceUrl.defaultZone: http://localhost:8010/eureka/
---
spring:
  profiles: subject
words: Ik,Gij,Hij,Zij,Het

---
spring:
  profiles: verb
words: rende,wist,gaf,zag,kocht

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog  
